In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,12]], np.int16)

# Mostrar a matriz completa
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 12]]


In [3]:
np.linalg.det(x)

-8.999999999999998

In [4]:
inversa = np.linalg.inv(x)
inversa

array([[-1.33333333,  0.        ,  0.33333333],
       [ 0.66666667,  1.        , -0.66666667],
       [ 0.33333333, -0.66666667,  0.33333333]])

In [ ]:
import time

t0 = time.time()

np.matmul(matriz1, matriz2)

t1 = time.time() - t0

print(t1)

0.2593193054199219


In [ ]:
t0 = time.time()

for i in range(len(matriz1)):
    
    for j in range(len(matriz2)):

        matriz1[i][j] * matriz2[j][i]

        # print(matriz1[i][j], matriz2[j][i])

t1 = time.time() - t0

print(t1)

0.07146930694580078
